#!/usr/bin/env bash

chmod -R 777 /var/www/html/storage
chmod -R 777 /var/www/html/bootstrap/cache
composer install
#php artisan config:cache
php artisan key:generate
php artisan optimize
php artisan migrate --force
# php artisan migrate:fresh --force
# php artisan db:seed
npm i
npm run build

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    if [ "$WORKER_MODE" = "true" ]; then
        exec /usr/bin/supervisord -c /etc/supervisor/conf.d/worker.conf
    else
        exec /usr/bin/supervisord -c /etc/supervisor/conf.d/webserver.conf
    fi
fi
